# Generated by Django 4.2.16 on 2024-11-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaukriJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_category', models.CharField(max_length=50)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('experience', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
